branch-defaults:
  main:
    environment: Markovcaricatures-env
environment-defaults:
  Markovcaricatures-env:
    branch: main
    repository: origin
global:
  application_name: Markov Caricatures
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
